/****** Object:  Table [dbo].[PShopInventory]    Script Date: 31/01/2021 16:54:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PShopInventory](
	[Name] [varchar](10) NOT NULL,
	[Text] [varchar](44) NOT NULL,
	[Items] [varbinary](1920) NULL,
 CONSTRAINT [PK_PShopInventory] PRIMARY KEY CLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

